### ISSUE TITLE
Incorrect evaluation of teacher role

### ISSUE THREAD

**Issue by mudrd8mz** [MoodleBeclever/Chalmers#1]
It is wrong to evaluate teachers via hard-coded role ID as in

https://github.com/MoodleBeclever/Chalmers/blob/b6453163940890732d960cf810b142a24eecaa7c/locallib.php#L387-L404

Different sites can have different role IDs. Things like this should be always evaluated via capabilities, not roles.

Ref: https://twitter.com/mudrd8mz/status/1339225992930488320

**Comment by MoodleBeclever** [comment]
Hello,

We've commited the fixes to the main branch.
